config/routes.rb
FirstDemo::Application.routes.draw do
  resources :static_pages

  resources :blogs do
   resources :comments
end

  get "home/index"

  root :to => 'blogs#index'

end

app/models/blog.rb
# -*- encoding : utf-8 -*-
class Blog < ActiveRecord::Base
  attr_accessible :content, :name, :title,:tags_attributes
  validates :name, :presence=>true
  validates :title,:presence=>true,:length =>{:minimum=>5}
  has_many :comments,:dependent => :destroy
  has_many :tags
  accepts_nested_attributes_for :tags,:allow_destroy =>:true,:reject_if => proc { |atters| atters.all? { |k,v| v.blank?  }}
end

app/models/comment.rb
# -*- encoding : utf-8 -*-
class Comment < ActiveRecord::Base
  
  attr_accessible :body, :commenter,:blog

  belongs_to :blog
end

app/models/static_page.rb
# -*- encoding : utf-8 -*-
class StaticPage < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/tag.rb
# -*- encoding : utf-8 -*-
class Tag < ActiveRecord::Base
  attr_accessible :name,:blog_id
  belongs_to :blog
  
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
# -*- encoding : utf-8 -*-
#-*- coding:utf-8 -*-
class BlogsController < ApplicationController
   http_basic_authenticate_with :name => 'yixichen', :password =>'123456',:except =>[:index,:show]
  # GET /blogs
  # GET /blogs.json
 respond_to 'html','js','xml'
  def index
    @blogs = Blog.all
    respond_with @blogs
   #respond_to do |format|
     #format.html # index.html.erb
      #format.json { render json: @blogs }
    #end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new
    respond_with @blogs
    #respond_to do |format|
     # format.html # new.html.erb
     # format.json { render json: @blog }
    #end

  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
 
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])
    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        print "出异常了。。。。"
        format.html { redirect_to @blog, notice: '成功更新帖子.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
# -*- encoding : utf-8 -*-
#-*- coding:utf-8 -*-
class CommentsController < ApplicationController
	http_basic_authenticate_with :name =>'yixichen', :password => '123456',:only =>:destroy
	def create
		@blog=Blog.find(params[:blog_id])
		@comment=@blog.comments.create(params[:comment])
		redirect_to blog_path(@blog)
	end
	def destroy
		params.each { |key,value| puts "出来了吗？#{key} => #{value}"}
		@blog=Blog.find(params[:blog_id])
		@comment=@blog.comments.find(params[:id])
		@comment.destroy
		redirect_to blog_path(@blog)
	end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
# -*- encoding : utf-8 -*-
class StaticPagesController < ApplicationController
  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @static_pages }
    end
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/new
  # GET /static_pages/new.json
  def new
    @static_page = StaticPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/1/edit
  def edit
    @static_page = StaticPage.find(params[:id])
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(params[:static_page])

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render json: @static_page, status: :created, location: @static_page }
      else
        format.html { render action: "new" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /static_pages/1
  # PUT /static_pages/1.json
  def update
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      if @static_page.update_attributes(params[:static_page])
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def join_tags(blog)
		blog.tags.map { |e| e.name  }.join(",")	
	end
end

app/helpers/comments_helper.rb
# -*- encoding : utf-8 -*-
#-*- coding:utf-8-*-
module CommentsHelper
	=begin
def just_test
		"是不是只要是module就能调用啊"
	end
	=end

end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/static_pages_helper.rb
# -*- encoding : utf-8 -*-
module StaticPagesHelper
end

app/views/blogs/_form.html.erb
<% @blog.tags.build  %>
<%= form_for @blog do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名称 %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :标题 %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :内容 %><br />
    <%= f.text_area :content %>
  </div>
  <h2>Tags</h2>
  <%= render :partial => 'tags/form',  :locals => {:form => f} %>
  <div class="actions">
    <%= f.submit '提交' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to '详细', @blog %> |
<%= link_to '返回', blogs_path %>

app/views/blogs/index.html.erb
<h1>欢迎.........</h1>

<table>
  <tr>
    <th>名称</th>
    <th>主题</th>
    <th>内容</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.name %></td>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '详细', blog %></td>
    <td><%= link_to '编辑', edit_blog_path(blog) %></td>
    <td><%= link_to '删除', blog, method: :delete, data: { confirm: '确定删除吗?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新增一个试试看', new_blog_path %>

app/views/blogs/new.html.erb
<h1>新增 blog</h1>

<%= render 'form' %>

<%= link_to '返回', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice  %></p>

<p>
  <b>名称:</b>
  <%= @blog.name %>
</p>

<p>
  <b>标题:</b>
  <%= @blog.title %>
</p>

<p>
  <b>内容:</b>
  <%= @blog.content %>
</p>
 <p>
   <b>标签：</b>
    <%= join_tags @blog %>  
 </p>
<H2>评论列表</H2>
<%= render @blog.comments %>
<h2>添加评论:<h2>
<%= form_for([@blog,@blog.comments.build]) do |f| %>
<div class="field">
	<%=f.label "主题" %><br/>
	<%=f.text_field :commenter %>
</div>
<div class="field">
        <%=f.label "内容" %><br/>
        <%=f.text_field :body %>
</div>
<div class="actions">
 <%= f.submit  "提交" %>
</div>
<% end %>
<%= link_to "编辑", edit_blog_path(@blog) %> |
<%= link_to '返回', blogs_path %>

app/views/comments/_comment.html.erb
<p>
	<b>主题：</b>
	<%= comment.commenter %>
</p>
<p>
	<b>内容：</b>
	<%= comment.body %>
</p>

<p>
	<%= link_to "Destroy Comment" ,[comment.blog,comment],  :confirm =>"确认删除吗？",
	:method => :delete%>

</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background:#EEEEEE">

<%= yield %>

</body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @static_pages.each do |static_page| %>
  <tr>
    <td><%= link_to 'Show', static_page %></td>
    <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
    <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |f| %>
	<div class="field">
		<%= f.label :name, '标签：' %>
		<%= f.text_field :name  %>
	</div>
	<% unless f.object.nil? || f.object.new_record? %>
    <div class="field">
      <%= f.label :_destroy, '移除:' %>
      <%= f.check_box :_destroy %>
    </div>
  <% end %>
<% end %> 